config/routes.rb
DsAlpha::Application.routes.draw do
  
  resources :posts, :users
  
  match 'login' => 'sessions#login', as: :login
  match 'sessions' => 'sessions#create'
  match 'logout' => 'sessions#logout', as: :logout
  
  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  image_accessor :image
  
end

app/models/user.rb
class User < ActiveRecord::Base  
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  # before_filter :login_user!, except: [:show, :index]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :login_user!, except: [:index, :show]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to :root
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to :root
    end
  end
  
  def destroy

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :login_user!, only: [:logout]
  def login
    
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user.present?
      if user.authenticate(params[:password])
        session[:user] = user.id
        redirect_to root_url
      else
        render :new
      end
    else
      render :new
    end
  end
  
  def logout
    reset_session
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # before_filter :is_admin?, except: [:update, :edit]
  
  def index
    @user = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save
    redirect_to :users
  end
  
  def edit
    @user = User.find_by_id(params[:id])
  end
  
  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(params[:user])
  end
  
  def delete  
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to :users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
  include AutoHtml
  
  def asset_embed(url)
      auto_html(url) {
      html_escape
      image
      youtube(:width => 400, :height => 250)
      link :target => "_blank", :rel => "nofollow"
      simple_format
      }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # def is_admin?
  #   current_user.admin.present?
  # end    
  
  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end
  
  def login_user!
    if current_user.nil?
      redirect_to login_url
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DsAlpha</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:multipart => true} do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label "Country" %>
  <%= f.select :country, [["United States"], ["Uganda"], ["Thailand"], ["Honduras"], ["Cambodia"], ["Vietnam"]] %>
  </p>
  <p>
  <%= f.label :asset_url %>
  <%= f.text_field :asset_url %>
  </p>
  <p>
  <%= f.label :image %>
  <%= f.file_field :image %>
  </p>
  <p>
  <%= f.label :description %>
  <%= f.text_field :description %>
  </p>
  <p>
  <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing: <em><%= @post.title %></em></h1>
<%= render 'posts/form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<ol>
  <% @posts.each do |p| %>
    <li>
    <%= link_to p.title, post_url(p) %>
    </li>
  <% end %>
</ol>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div>
  <%= asset_embed(@post.asset_url) %>
</div>
<div>
  <%= image_tag @post.image.url if @post.image_uid.present? %>
</div>
<p><%= @post.description %></p>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_for @user do |user| %>
  <%= user.label "Name" %>
  <%= user.text_field :name %>
  <%= user.label "Email" %>
  <%= user.email_field :email required %>
  <%= user.label "Password" %>
  <%= user.password_field :password required %>
  <%= user.password_field :password_confirmation %>
<% end %>

app/views/users/index.html.erb
<h1>All User</h1>
<% @user.each do |u| %>
  <%= u.email %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user do |user| %>
  <%= user.label "Name" %>
  <%= user.text_field :name %>
  <%= user.label "Email" %>
  <%= user.email_field :email %>
  <%= user.label "School" %>
  <%= user.select :school, options_for_select(["Huy Ping May, Thailand", "Stonybrook, US"]) %>
  <%= user.label "Admin" %>
  <%= user.check_box :admin %>
  <%= user.label "Password" %>
  <%= user.password_field :password %>
  <%= user.label "Password Confirmation" %>
  <%= user.password_field :password_confirmation %>
  <%= user.submit "Create User" %>
<% end %>